Guardian_Web/Controllers/AuthController.cs
using Guardian_Utility;
using Guardian_Web.Models.API;
using Guardian_Web.Models.DTO.LoginUser;
using Guardian_Web.Models.DTO.LoginUser.Registration;
using Guardian_Web.Services.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace Guardian_Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDTO obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDTO obj)
        {
            APIResponse response = await _authService.LoginAsync<APIResponse>(obj);
            if (response != null && response.IsSuccess)
            {
                LoginResponseDTO model = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(response.Result));

                #region Sign in / Saving session infos
                var handler = new JwtSecurityTokenHandler(); //The token has the informations we need (Name and role)
                var jwt = handler.ReadJwtToken(model.Token);
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(u => u.Type == "unique_name").Value));
                identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal); //Sign the user (save user infos to be used in session)
                #endregion

                HttpContext.Session.SetString(SD.SessionToken, model.Token);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("CustomError", response.ErrorMessages.FirstOrDefault());
                return View(obj);
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            RegistrationResquestDTO obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegistrationResquestDTO obj)
        {
            APIResponse result = await _authService.RegisterAsync<APIResponse>(obj);
            if (result != null && result.IsSuccess)
            {
                return RedirectToAction("Login");
            }
            return View(obj);
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString(SD.SessionToken, ""); //Cleaning the session when the user logout
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult AcessDenied()
        {
            return View();
        }
    }
}

Guardian_Web/Controllers/GuardianController.cs
using AutoMapper;
using Guardian_Utility;
using Guardian_Web.Models.API;
using Guardian_Web.Models.DTO.Guardian;
using Guardian_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Reflection;

namespace Guardian_Web.Controllers
{
    public class GuardianController : Controller
    {
        private readonly IGuardianService _guardianService;
        private readonly IMapper _mapper;

        public GuardianController(IGuardianService guardianService, IMapper mapper)
        {
            _guardianService = guardianService;
            _mapper = mapper;
        }

        public async Task<IActionResult> IndexGuardian()
        {
            List<GuardianDTO> list = new();

            var response = await _guardianService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<GuardianDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateGuardian()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGuardian(GuardianCreateDTO model)
        {
            model.CreatedDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                var response = await _guardianService.CreateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.IsSuccess)
                {
                    //Redirect back to the index action method that willl reaload al the table informations
                    TempData["success"] = "Registred successfully"; //Sweet alert
                    return RedirectToAction(nameof(IndexGuardian));
                }
            }
            TempData["error"] = "Error encounted.";
            return View(model);
        }
        
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateGuardian(int guardianId)
        {
            var response = await _guardianService.GetAsync<APIResponse>(guardianId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                GuardianDTO model = JsonConvert.DeserializeObject<GuardianDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<GuardianUpdateDTO>(model));
            }
            return NotFound();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateGuardian(GuardianUpdateDTO model)
        {
            var getGuardian = await _guardianService.GetAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));

            if (getGuardian != null && getGuardian.IsSuccess)
            {
                GuardianDTO guardian = JsonConvert.DeserializeObject<GuardianDTO>(Convert.ToString(getGuardian.Result));
                model.CreatedDate = guardian.CreatedDate;
                model.UpdatedDate = DateTime.Now;
            }

            if (ModelState.IsValid)
            {
                var response = await _guardianService.UpdadeAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.IsSuccess)
                {
                    //Redirect back to the index action method that willl reaload al the table informations
                    TempData["success"] = "Updated successfully"; //Sweet alert
                    return RedirectToAction(nameof(IndexGuardian));
                }
            }
            TempData["error"] = "Error encounted.";
            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteGuardian(int guardianId)
        {
            var response = await _guardianService.GetAsync<APIResponse>(guardianId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                GuardianDTO model = JsonConvert.DeserializeObject<GuardianDTO>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteGuardian(GuardianDTO model)
        {
            var response = await _guardianService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Removed successfully";
                return RedirectToAction(nameof(IndexGuardian));
            }
            TempData["error"] = "Error encounted.";
            return View(model);
        }
    }
}

Guardian_Web/Controllers/GuardianTaskController.cs
using AutoMapper;
using Guardian_Utility;
using Guardian_Web.Models.API;
using Guardian_Web.Models.DTO.Guardian;
using Guardian_Web.Models.DTO.GuardianTask;
using Guardian_Web.Models.ViewModel;
using Guardian_Web.Services;
using Guardian_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Data;

namespace Guardian_Web.Controllers
{
    public class GuardianTaskController : Controller
    {
        private readonly IGuardianTaskService _guardianTaskService;
        private readonly IGuardianService _guardianService;
        private readonly IMapper _mapper;

        public GuardianTaskController(IGuardianTaskService guardianTaskService, IGuardianService guardianService, IMapper mapper)
        {
            _guardianTaskService = guardianTaskService;
            _guardianService = guardianService;
            _mapper = mapper;
        }

        public async Task<IActionResult> IndexGuardianTask()
        {
            List<GuardianTaskDTO> list = new();

            var response = await _guardianTaskService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<GuardianTaskDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        public async Task<IActionResult> CreateTaskGuardian()
        {
            GuardianTaskCreateVM guardianTaskVM = new();

            var response = await _guardianService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                //Populate  the dropdown
                guardianTaskVM.GuardianList = JsonConvert.DeserializeObject<List<GuardianDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }
            return View(guardianTaskVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTaskGuardian(GuardianTaskCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _guardianTaskService.CreateAsync<APIResponse>(model.Guardian, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.IsSuccess)
                {
                    //Redirect back to the index action method that willl reaload al the table informations
                    TempData["success"] = "Updated successfully";
                    return RedirectToAction(nameof(IndexGuardianTask));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            //Populate the dropdaown again if the response is invalid
            var res = await _guardianService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (res != null && res.IsSuccess)
            {
                //Populate  the dropdown
                model.GuardianList = JsonConvert.DeserializeObject<List<GuardianDTO>>
                    (Convert.ToString(res.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }
            TempData["error"] = "Error encounted.";
            return View(model);
        }

        public async Task<IActionResult> UpdateTaskGuardian(int guardianTaskId)
        {
            GuardianTaskUpdateVM guardianTaskVM = new();

            var response = await _guardianTaskService.GetAsync<APIResponse>(guardianTaskId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                GuardianTaskDTO model = JsonConvert.DeserializeObject<GuardianTaskDTO>(Convert.ToString(response.Result));
                guardianTaskVM.GuardianTask = _mapper.Map<GuardianUpdateTaskDTO>(model);
            }

            response = await _guardianService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                //Populate  the dropdown
                guardianTaskVM.GuardianList = JsonConvert.DeserializeObject<List<GuardianDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });

                return View(guardianTaskVM);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTaskGuardian(GuardianTaskUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _guardianTaskService.UpdadeAsync<APIResponse>(model.GuardianTask, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.IsSuccess)
                {
                    //Redirect back to the index action method that willl reaload al the table informations
                    TempData["success"] = "Updated successfully";
                    return RedirectToAction(nameof(IndexGuardianTask));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }

            }

            //Populate the dropdaown again if the response is invalid
            var res = await _guardianService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (res != null && res.IsSuccess)
            {
                //Populate  the dropdown
                model.GuardianList = JsonConvert.DeserializeObject<List<GuardianDTO>>
                    (Convert.ToString(res.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }
            TempData["error"] = "Error encounted.";
            return View(model);
        }

        public async Task<IActionResult> DeleteTaskGuardian(int guardianTaskId)
        {
            var response = await _guardianTaskService.GetAsync<APIResponse>(guardianTaskId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                GuardianTaskDTO model = JsonConvert.DeserializeObject<GuardianTaskDTO>(Convert.ToString(response.Result));

                if (model != null)
                {
                    if (response != null && response.IsSuccess)
                    {
                        return View(model);
                    }
                }
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTaskGuardian(GuardianTaskDTO model)
        {
            var response = await _guardianTaskService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Removed successfully";
                return RedirectToAction(nameof(IndexGuardianTask));
            }
            TempData["error"] = "Error encounted.";
            return View(model);
        }
    }
}

Guardian_Web/Views/Shared/_Layout.cshtml
@using Guardian_Utility;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc //Injection to access session informations - It need to have dependency injection in program.cs//

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Guardian_Web</title>
    <link rel="stylesheet" href="~/css/bootstrapStyle.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Guardian_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Guardian Task Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Guardian" asp-action="IndexGuardian">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GuardianTask" asp-action="IndexGuardianTask">Tasks</a>
                        </li>

                        @if (httpAcc.HttpContext.Session.GetString(SD.SessionToken) != null
                        && httpAcc.HttpContext.Session.GetString(SD.SessionToken).ToString().Length > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2023 Guardian - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script> @*Add sweet alert in "base page" if you want to use sweetalert without _Notification partial later on*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Guardian_Web/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}

@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}